### ISSUE TITLE
change the message _ amount of 2.6 

### ISSUE THREAD

**Issue by BeataKwiecinska** [DabTheMatt/balance#39]
when I enter the amount of 2.6, I get a message in Polish, enter the correct value
the English version should probably be in English, and there should be a message to give a rounded value to one
<img width="522" alt="Zrzut ekranu 2020-10-20 o 11 37 21" src="https://user-images.githubusercontent.com/65465191/96568876-b8e97980-12c8-11eb-864d-6d788c8211bb.png">

**Comment by DabTheMatt** [comment]
Fix, allow two decimal places in input (cost)
